### ISSUE TITLE
folder "rgtdata" is missing

### ISSUE THREAD

**Issue by ericeric0827** [CostaLab/reg-gen#110]
Hello everyone,
I am trying to install RGT by following the guideline, however I meet some problems.
I installed everything including
pip install --user cython numpy scipy
pip install --user RGT
and it showed already installed or satisfied, so I keep going to next step which install the genomic data.
Now the problem is "I don't have folder rgtdata"!!, the message is:
cheng-kaide-MacBook-Pro:~ cheng-kaihuang$ cd ~/rgtdata
-bash: cd: /Users/cheng-kaihuang/rgtdata: No such file or directory
Now I am using 2017 macbook pro, macOS Mojave 10.14.3
Could someone help me?
Thank you very much!

**Comment by fabio-t** [comment]
Hi, this can be solved by running pip like this:

```
pip install --user RGT --no-binary rgt
```

We will do some testing with the next release and see if this is now always needed for Mac OS, in which case we'll [update the documentation](https://regulatory-genomics.org/rgt/download-installation/#mac-installation).

Note that, since you are using `--user` on Mac, you'll need to add `/Users/Library/Python/2.7/bin` to your PATH, or you won't be be able to easily run the programs `rgt-hint`, `rgt-TDF` etc.
