### ISSUE TITLE
gcc compile  version of libtriplexator.so

### ISSUE THREAD

**Issue by xflicsu** [CostaLab/reg-gen#16]
Hello, I download the new version of reg-gen.
But my gcc is 4.4.6. 
Then, I caught the error as follows:

libtriplexator.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found

And the  `GLIBCXX_3.4.15' is coresponding to gcc 4.6.0.
So, could you compile libtriplexator.so with lower gcc version?

Thanks!

**Comment by fabioticconi** [comment]
Hi @xflicsu, we are going to fix this soon hopefully, but for now you could take the sources from here and recompile it yourself: https://github.com/CostaLab/reg-gen/tree/master/c

Then manually overwrite the library.

**Comment by xflicsu** [comment]
Thanks @fabioticconi !
The "librgt.so" works well. 
But I can not find scripts to compile into libtriplexator.so.

**Comment by fabioticconi** [comment]
Sorry, I misread ;) I will see what I can do about triplexator.

**Comment by fabioticconi** [comment]
With older versions of gcc, it can be solved by compiling triplexator directly (as a shared library) and substituting it to the one we ship it with.

Ref: https://github.com/zbarni/triplexator/issues/1 that repository has all instructions needed to compile triplexator.

Closing here, since this is a bit of an edge case that we aren't probably going to solve.
