### ISSUE TITLE
HINT-ATAC, atac_bias_table_F.txt

### ISSUE THREAD

**Issue by YichaoOU** [CostaLab/reg-gen#161]
Hello,

From the HINT-ATAC paper, I think the Tn5 bias correction is estimated from the given ATAC-seq data, right? So then what are the bias table in `rgdata/fp_hmms/`? 

Thanks,
Yichao

**Comment by lzj1769** [comment]
Hi Yichao,

this table contains the bias that we pre-computed by using good quality ATAC-seq data, since estimating bias from the given ATAC-seq is computation expensive, and we here try to reduce the running time by providing this table. You can also estimate a new table using rgt and use it for footprinting. see `rgt-hint` for more information.

Best,
Li
