### ISSUE TITLE
Use rel. paths in HTML report

### ISSUE THREAD

**Issue by mpi-pebert** [CostaLab/reg-gen#22]
Hi,
I have a suggestion for improvement - apparently, the HTML report uses full paths to link to the image files, which makes sharing the report a bit complicated (i.e., in our setup, the cluster file system is isolated from the rest, so the report files have to copied somewhere else).
Best,
Peter

**Comment by fabioticconi** [comment]
The fix will be in in the next release. Thanks for reporting!

In particular,

* the RGT logo, js and CSS files, currently with absolute path of the user's rgtdata folder, are now copied in the report folder and relative paths added to HTML
* the pics are referenced with relative paths in the HTML
* the BAM files are listed in the table with their absolute path, since when the report directory is moved around (eg, given to collegues) it usually doesn't mean you also move the BAM files. It can be useful to track back the specific files used in the generation of the report.
