### ISSUE TITLE
p-value in BED output files

### ISSUE THREAD

**Issue by mpi-pebert** [CostaLab/reg-gen#23]
Hi,
I just checked some of the output BED files (`THOR 0.9.8`) and realized that the p-value column contains several times the following number:
```bash
15483:12140:16917;25102:20718:22467;9223372036854775807
14791:11131:14713;24211:20379:20588;9223372036854775807
26633:25513:31360;51481:39765:42614;9223372036854775807

9223372036854775807
```
The number is so popular that it has its own Wikipedia page...
```python
2**63 − 1
```
I presume there is a numerical/floating point issue/`sys.maxsize` default or the like at the core of this.

+Peter

**Comment by fabioticconi** [comment]
Well, good spot! Thank you.

**Comment by fabioticconi** [comment]
OK, so this is not *actually* a bug. In a way. Problem is, sometimes the produced p-value is so small we get it as 0 (or maybe it's actually 0). That produces a Phred-score output of infinity, of course:

```
>>> -np.log10(0) == float("inf")
True
```

So we use `sys.maxint` to write something numeric in the BED file.

I guess we could find what's the smallest p-value producible and use the `-log10` of that instead of sys.maxint. It's a much smaller number - it is in fact around `323`. But I need to think about whether this number is stable across platforms - and it might not scale in the future.

For now, we won't fix it - you can consider that big number as a constant representing a p-value of zero.
